<?php

/** @var \Illuminate\Database\Eloquent\Factory $factory */

use App\Models\Article;
use App\Models\Category;
use Faker\Generator as Faker;

use function GuzzleHttp\Psr7\str;

$factory->define(Article::class, function (Faker $faker) {
    $title = $faker->sentence; // random sentence generated by Laravel
    return [
        'title' => $title,
        'slug' => str_slug($title),
        'body' => $faker->text,
        'category_id' => function () {
            return Category::all()->random();
        },
        'tags' => '',
        'close_to_comment' => rand(1,2),
        'is_live' => rand(1,2)
    ];
});
